### ISSUE TITLE
GitHub Actions Gradle Integration Test

### ISSUE THREAD

**Issue by ooMia** [spring-templates/spring-concurrency-thread#3]
기존 Java-Lotto 내용 import

```yaml
name: Run gradlew clean test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run gradlew clean test
      run: ./gradlew clean test
```
